### ISSUE TITLE
Error when sending email via tls port 587, bad record mac

### ISSUE THREAD

**Issue by rossilazuardi** [Vagabond/gen_smtp#162]
Hi.
I try to send email via port 587, smpt.gmail.com , because it the only port allowed by my provider.
but got this error {error,{tls_alert,"bad record mac"}}
i try to do telnet on that port.. and it connected.
anyone can help?

**Comment by oKarolMoroz** [comment]
Hi,
I am not sure if this will help you, but I had the same issue using swoosh, an email-sending library for Elixir based on gen_smtp. I spent more than two hours pulling hairs because of this issue.
In the [SMTP adapter settings](https://hexdocs.pm/swoosh/Swoosh.Adapters.SMTP.html#content), I set `ssl: false`, which revealed the actual problem. It turned out that I could not authenticate my Gmail account due to Gmail's elevated security standards. This has been explained in #151. When I set "allow less secure apps" to ON in Google account settings, the problem was solved.
