### ISSUE TITLE
Publish to Hex package to 

### ISSUE THREAD

**Issue by mworrell** [Vagabond/gen_smtp#78]
Hex is a package manager for Elixir (and Erlang) -- making a Hex package makes it a lot easier to use in Elixir projects.

It'd be great if you could publish it to Hex too -- I could do it, but you probably want to make your own releases.

https://hex.pm/docs/publish

@Vagabond @keichan34

This is a followup issue from #77

**Comment by Vagabond** [comment]
I'm fine with someone else being the point of contact for this, otherwise it might take some time for me to set up all the prerequisities.

**Comment by mworrell** [comment]
Me too, @keichan34 would you like to do this?

**Comment by keichan34** [comment]
No problem.

Published: https://hex.pm/packages/gen_smtp

I've watched the repository; I'll make new releases as necessary :smiley:

**Comment by mworrell** [comment]
Thank you!  Leaving this open till it is merged in Hex.

**Comment by keichan34** [comment]
It's published, see: https://hex.pm/packages/gen_smtp . The other PRs mentioning this issue are referring to other projects that are switching to using the Hex version instead of directly downloading it from GitHub.

Are there any changes you want me to make? I just set "Contributors" to "Vagabond" because it was the name of the owner repository, but we should probably change that. License, too.

**Comment by JustMikey** [comment]
@keichan34 Can you add the info about the other main maintainers and the license so this issue could be closed?
