### ISSUE TITLE
Remove deprecated eiconv dependency

### ISSUE THREAD

**Issue by edevil** [Vagabond/gen_smtp#95]
eiconv has been deprecated as per https://github.com/processone/eiconv

It would be nice to switch to the supported iconv lib: https://github.com/processone/iconv/

**Comment by mworrell** [comment]
`gen_smtp` is referring to the similarly named https://github.com/zotonic/eiconv, not to the ProcessOne eiconv

**Comment by mworrell** [comment]
We are using the Zotonic `eiconv` because the other NIFs block the scheduler on large input texts. The Zotonic eiconv solves this by chopping the input into smaller chunks and converting those chunks one by one.

A quick inspection of the ProcessOne `iconv` shows that they don't have a routine to chunk the input, so I expect it will block the Erlang scheduler on large inputs.

I suggest to either stick with Zotonic `eiconv` or see if you can get the chunking merged into the ProcessOne version.

**Comment by seriyps** [comment]
Can be closed?

**Comment by mworrell** [comment]
I think it can be closed, maybe revisit when the ProcessOne iconv lib supports chunks.
